// Code generated by solo-kit. DO NOT EDIT.

package v1

import (
	"github.com/solo-io/go-utils/contextutils"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients"
	"github.com/solo-io/solo-kit/pkg/api/v1/reconcile"
	"github.com/solo-io/solo-kit/pkg/api/v1/resources"
)

// Option to copy anything from the original to the desired before writing. Return value of false means don't update
type TransitionGoogleApiKeyFunc func(original, desired *GoogleApiKey) (bool, error)

type GoogleApiKeyReconciler interface {
	Reconcile(namespace string, desiredResources GoogleApiKeyList, transition TransitionGoogleApiKeyFunc, opts clients.ListOpts) error
}

func googleApiKeysToResources(list GoogleApiKeyList) resources.ResourceList {
	var resourceList resources.ResourceList
	for _, googleApiKey := range list {
		resourceList = append(resourceList, googleApiKey)
	}
	return resourceList
}

func NewGoogleApiKeyReconciler(client GoogleApiKeyClient) GoogleApiKeyReconciler {
	return &googleApiKeyReconciler{
		base: reconcile.NewReconciler(client.BaseClient()),
	}
}

type googleApiKeyReconciler struct {
	base reconcile.Reconciler
}

func (r *googleApiKeyReconciler) Reconcile(namespace string, desiredResources GoogleApiKeyList, transition TransitionGoogleApiKeyFunc, opts clients.ListOpts) error {
	opts = opts.WithDefaults()
	opts.Ctx = contextutils.WithLogger(opts.Ctx, "googleApiKey_reconciler")
	var transitionResources reconcile.TransitionResourcesFunc
	if transition != nil {
		transitionResources = func(original, desired resources.Resource) (bool, error) {
			return transition(original.(*GoogleApiKey), desired.(*GoogleApiKey))
		}
	}
	return r.base.Reconcile(namespace, googleApiKeysToResources(desiredResources), transitionResources, opts)
}
