// Code generated by solo-kit. DO NOT EDIT.

package v1

import (
	"github.com/solo-io/go-utils/contextutils"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients"
	"github.com/solo-io/solo-kit/pkg/api/v1/reconcile"
	"github.com/solo-io/solo-kit/pkg/api/v1/resources"
)

// Option to copy anything from the original to the desired before writing. Return value of false means don't update
type TransitionPresentationFunc func(original, desired *Presentation) (bool, error)

type PresentationReconciler interface {
	Reconcile(namespace string, desiredResources PresentationList, transition TransitionPresentationFunc, opts clients.ListOpts) error
}

func presentationsToResources(list PresentationList) resources.ResourceList {
	var resourceList resources.ResourceList
	for _, presentation := range list {
		resourceList = append(resourceList, presentation)
	}
	return resourceList
}

func NewPresentationReconciler(client PresentationClient) PresentationReconciler {
	return &presentationReconciler{
		base: reconcile.NewReconciler(client.BaseClient()),
	}
}

type presentationReconciler struct {
	base reconcile.Reconciler
}

func (r *presentationReconciler) Reconcile(namespace string, desiredResources PresentationList, transition TransitionPresentationFunc, opts clients.ListOpts) error {
	opts = opts.WithDefaults()
	opts.Ctx = contextutils.WithLogger(opts.Ctx, "presentation_reconciler")
	var transitionResources reconcile.TransitionResourcesFunc
	if transition != nil {
		transitionResources = func(original, desired resources.Resource) (bool, error) {
			return transition(original.(*Presentation), desired.(*Presentation))
		}
	}
	return r.base.Reconcile(namespace, presentationsToResources(desiredResources), transitionResources, opts)
}
