// Code generated by solo-kit. DO NOT EDIT.

package v1

import (
	"github.com/solo-io/solo-kit/pkg/api/v1/clients"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients/factory"
	"github.com/solo-io/solo-kit/pkg/api/v1/resources"
	"github.com/solo-io/solo-kit/pkg/errors"
)

type PresentationWatcher interface {
	// watch namespace-scoped Presentations
	Watch(namespace string, opts clients.WatchOpts) (<-chan PresentationList, <-chan error, error)
}

type PresentationClient interface {
	BaseClient() clients.ResourceClient
	Register() error
	Read(namespace, name string, opts clients.ReadOpts) (*Presentation, error)
	Write(resource *Presentation, opts clients.WriteOpts) (*Presentation, error)
	Delete(namespace, name string, opts clients.DeleteOpts) error
	List(namespace string, opts clients.ListOpts) (PresentationList, error)
	PresentationWatcher
}

type presentationClient struct {
	rc clients.ResourceClient
}

func NewPresentationClient(rcFactory factory.ResourceClientFactory) (PresentationClient, error) {
	return NewPresentationClientWithToken(rcFactory, "")
}

func NewPresentationClientWithToken(rcFactory factory.ResourceClientFactory, token string) (PresentationClient, error) {
	rc, err := rcFactory.NewResourceClient(factory.NewResourceClientParams{
		ResourceType: &Presentation{},
		Token:        token,
	})
	if err != nil {
		return nil, errors.Wrapf(err, "creating base Presentation resource client")
	}
	return NewPresentationClientWithBase(rc), nil
}

func NewPresentationClientWithBase(rc clients.ResourceClient) PresentationClient {
	return &presentationClient{
		rc: rc,
	}
}

func (client *presentationClient) BaseClient() clients.ResourceClient {
	return client.rc
}

func (client *presentationClient) Register() error {
	return client.rc.Register()
}

func (client *presentationClient) Read(namespace, name string, opts clients.ReadOpts) (*Presentation, error) {
	opts = opts.WithDefaults()

	resource, err := client.rc.Read(namespace, name, opts)
	if err != nil {
		return nil, err
	}
	return resource.(*Presentation), nil
}

func (client *presentationClient) Write(presentation *Presentation, opts clients.WriteOpts) (*Presentation, error) {
	opts = opts.WithDefaults()
	resource, err := client.rc.Write(presentation, opts)
	if err != nil {
		return nil, err
	}
	return resource.(*Presentation), nil
}

func (client *presentationClient) Delete(namespace, name string, opts clients.DeleteOpts) error {
	opts = opts.WithDefaults()

	return client.rc.Delete(namespace, name, opts)
}

func (client *presentationClient) List(namespace string, opts clients.ListOpts) (PresentationList, error) {
	opts = opts.WithDefaults()

	resourceList, err := client.rc.List(namespace, opts)
	if err != nil {
		return nil, err
	}
	return convertToPresentation(resourceList), nil
}

func (client *presentationClient) Watch(namespace string, opts clients.WatchOpts) (<-chan PresentationList, <-chan error, error) {
	opts = opts.WithDefaults()

	resourcesChan, errs, initErr := client.rc.Watch(namespace, opts)
	if initErr != nil {
		return nil, nil, initErr
	}
	presentationsChan := make(chan PresentationList)
	go func() {
		for {
			select {
			case resourceList := <-resourcesChan:
				presentationsChan <- convertToPresentation(resourceList)
			case <-opts.Ctx.Done():
				close(presentationsChan)
				return
			}
		}
	}()
	return presentationsChan, errs, nil
}

func convertToPresentation(resources resources.ResourceList) PresentationList {
	var presentationList PresentationList
	for _, resource := range resources {
		presentationList = append(presentationList, resource.(*Presentation))
	}
	return presentationList
}
