// Code generated by solo-kit. DO NOT EDIT.

package v1

import (
	"context"
	fmt "fmt"
	"time"

	"go.opencensus.io/stats"

	"github.com/solo-io/go-utils/errutils"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients"
)

type PresentationsSimpleEmitter interface {
	Snapshots(ctx context.Context) (<-chan *PresentationsSnapshot, <-chan error, error)
}

func NewPresentationsSimpleEmitter(aggregatedWatch clients.ResourceWatch) PresentationsSimpleEmitter {
	return NewPresentationsSimpleEmitterWithEmit(aggregatedWatch, make(chan struct{}))
}

func NewPresentationsSimpleEmitterWithEmit(aggregatedWatch clients.ResourceWatch, emit <-chan struct{}) PresentationsSimpleEmitter {
	return &presentationsSimpleEmitter{
		aggregatedWatch: aggregatedWatch,
		forceEmit:       emit,
	}
}

type presentationsSimpleEmitter struct {
	forceEmit       <-chan struct{}
	aggregatedWatch clients.ResourceWatch
}

func (c *presentationsSimpleEmitter) Snapshots(ctx context.Context) (<-chan *PresentationsSnapshot, <-chan error, error) {
	snapshots := make(chan *PresentationsSnapshot)
	errs := make(chan error)

	untyped, watchErrs, err := c.aggregatedWatch(ctx)
	if err != nil {
		return nil, nil, err
	}

	go errutils.AggregateErrs(ctx, errs, watchErrs, "presentations-emitter")

	go func() {
		originalSnapshot := PresentationsSnapshot{}
		currentSnapshot := originalSnapshot.Clone()
		timer := time.NewTicker(time.Second * 1)
		sync := func() {
			if originalSnapshot.Hash() == currentSnapshot.Hash() {
				return
			}

			stats.Record(ctx, mPresentationsSnapshotOut.M(1))
			originalSnapshot = currentSnapshot.Clone()
			sentSnapshot := currentSnapshot.Clone()
			snapshots <- &sentSnapshot
		}

		defer func() {
			close(snapshots)
			close(errs)
		}()

		for {
			record := func() { stats.Record(ctx, mPresentationsSnapshotIn.M(1)) }

			select {
			case <-timer.C:
				sync()
			case <-ctx.Done():
				return
			case <-c.forceEmit:
				sentSnapshot := currentSnapshot.Clone()
				snapshots <- &sentSnapshot
			case untypedList := <-untyped:
				record()

				currentSnapshot = PresentationsSnapshot{}
				for _, res := range untypedList {
					switch typed := res.(type) {
					case *Presentation:
						currentSnapshot.Presentations = append(currentSnapshot.Presentations, typed)
					case *GoogleApiKey:
						currentSnapshot.Googleapikeys = append(currentSnapshot.Googleapikeys, typed)
					default:
						select {
						case errs <- fmt.Errorf("PresentationsSnapshotEmitter "+
							"cannot process resource %v of type %T", res.GetMetadata().Ref(), res):
						case <-ctx.Done():
							return
						}
					}
				}

			}
		}
	}()
	return snapshots, errs, nil
}
